name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Install .NET quality tools
        run: |
          # Install global tools first
          dotnet tool install -g JetBrains.ReSharper.GlobalTools

          # Check if any .NET projects exist
          if [ -n "$(find . -name '*.csproj' -o -name '*.sln')" ]; then
            # Find the first .NET project directory
            PROJECT_DIR=$(dirname $(find . -name '*.csproj' -o -name '*.sln' | head -n 1))
            cd "$PROJECT_DIR"
            
            # Install analyzers at project level
            dotnet add package StyleCop.Analyzers
            dotnet add package Microsoft.CodeAnalysis.NetAnalyzers
            dotnet add package Microsoft.CodeAnalysis.CSharp.CodeStyle
            dotnet add package Roslynator.Analyzers
          else
            echo "No .NET projects found. Skipping analyzer package installation."
          fi

      - name: Create default configs
        run: |
          echo "root = true

          [*.{cs,vb}]
          dotnet_analyzer_diagnostic.severity = warning" > .editorconfig

          echo '{
            "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
            "settings": {
              "documentationRules": {
                "companyName": "YourCompany"
              }
            }
          }' > stylecop.json

      - name: Cache .NET tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.dotnet/tools
            ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: PR Review Bot
        uses: boredom1234/pr-review-bot-together@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          TOGETHER_API_MODEL: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
          enable_quality_metrics: true
          quality_tools: eslint,pylint,golint,roslyn,stylecop,resharper
          quality_config_paths: '{"eslint":".eslintrc.json","roslyn":".editorconfig","stylecop":"stylecop.json","resharper":"resharper.DotSettings"}'
          resharper_solution: ${{ github.workspace }}/*.sln
          ignore_rules: '{"eslint":["no-console","no-unused-vars"],"stylecop":["SA1633","SA1200"],"resharper":["RedundantUsingDirective"],"roslyn":["IDE0005"]}'
          ignore_files: "**/*.Designer.cs,**/obj/**,**/bin/**,**/*.g.cs"
          fail_on_quality_issues: false
          max_critical_issues: -1
          max_warning_issues: -1
          comment_mode: all
